[package]
name = "never-ending-txt"
version = "0.1.0"
edition = "2021"
authors = ["Gabriel Cruz <gabrieldemelocruz@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docopt = "*"
